-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "itemTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tipAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
